// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToyCabin.Infrastructure.Context;

#nullable disable

namespace ToyCabin.Infrastructure.Migrations
{
    [DbContext(typeof(ToyCabinDbContext))]
    [Migration("20260116094153_AddDbFull")]
    partial class AddDbFull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToyCabin.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFirstLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Salt")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Cabin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.CabinSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("TakenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CabinId", "TakenAt");

                    b.ToTable("CabinSnapshots");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.DamageMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DamageReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DamageReportId");

                    b.ToTable("DamageMedia");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.DamageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductColorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("DamageReports");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DispositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductColorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DispositionId");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("InventoryLocationId", "ProductColorId", "DispositionId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.InventoryDisposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InventoryDispositions");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.InventoryLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryLocations");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromDispositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductColorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ToDispositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromDispositionId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("ToDispositionId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("StoreId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductColorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("OrderId", "ProductColorId")
                        .IsUnique();

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("RevenueSharePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasComment("Revenue share percentage from 0 to 100");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("STANDARD");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.PasswordResetOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("PasswordResetOtps");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgeRange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsConsignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Material")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Model3DUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("QrCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ProductColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CabinId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CabinId", "Code")
                        .IsUnique();

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ShelfSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DisplayCapacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("IdealWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShelfId", "Code")
                        .IsUnique();

                    b.ToTable("ShelfSlots");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("FromLocationId", "ToLocationId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ShipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductColorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("ShipmentId", "ProductColorId")
                        .IsUnique();

                    b.ToTable("ShipmentItems");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ShipmentMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("ShipmentMedias");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StoreAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.StoreInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoreRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("StoreId", "UserId", "Status")
                        .HasDatabaseName("IX_StoreInvitation_Store_User_Status");

                    b.ToTable("StoreInvitations");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.UserStore", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("StoreRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("UserStores");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Account", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Account_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.AccountRole", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AccountRole_Account");

                    b.HasOne("ToyCabin.Domain.Entities.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AccountRole_Role");

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Cabin", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Store", "Store")
                        .WithMany("Cabins")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Cabin_Store");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.CabinSnapshot", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Cabin", "Cabin")
                        .WithMany("CabinSnapshots")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CabinSnapshot_Cabin");

                    b.HasOne("ToyCabin.Domain.Entities.User", "User")
                        .WithMany("CabinSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CabinSnapshot_User");

                    b.Navigation("Cabin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.DamageMedia", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.DamageReport", "DamageReport")
                        .WithMany("DamageMedia")
                        .HasForeignKey("DamageReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DamageMedia_DamageReport");

                    b.Navigation("DamageReport");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.DamageReport", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.InventoryLocation", "InventoryLocation")
                        .WithMany("DamageReports")
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DamageReport_InventoryLocation");

                    b.HasOne("ToyCabin.Domain.Entities.ProductColor", "ProductColor")
                        .WithMany("DamageReports")
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DamageReport_ProductColor");

                    b.HasOne("ToyCabin.Domain.Entities.User", "ReportedByUser")
                        .WithMany("ReportedDamageReports")
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DamageReport_ReportedByUser");

                    b.HasOne("ToyCabin.Domain.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedDamageReports")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DamageReport_ReviewedByUser");

                    b.Navigation("InventoryLocation");

                    b.Navigation("ProductColor");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.InventoryDisposition", "Disposition")
                        .WithMany("Inventories")
                        .HasForeignKey("DispositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Disposition");

                    b.HasOne("ToyCabin.Domain.Entities.InventoryLocation", "InventoryLocation")
                        .WithMany("Inventories")
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_InventoryLocation");

                    b.HasOne("ToyCabin.Domain.Entities.ProductColor", "ProductColor")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_ProductColor");

                    b.Navigation("Disposition");

                    b.Navigation("InventoryLocation");

                    b.Navigation("ProductColor");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.InventoryLocation", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Store", "Store")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("StoreId")
                        .HasConstraintName("FK_InventoryLocation_Store");

                    b.HasOne("ToyCabin.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_InventoryLocation_Warehouse");

                    b.Navigation("Store");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.InventoryDisposition", "FromDisposition")
                        .WithMany("FromInventoryTransactions")
                        .HasForeignKey("FromDispositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransaction_FromDisposition");

                    b.HasOne("ToyCabin.Domain.Entities.InventoryLocation", "FromLocation")
                        .WithMany("OutgoingInventoryTransactions")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransaction_FromLocation");

                    b.HasOne("ToyCabin.Domain.Entities.ProductColor", "ProductColor")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransaction_ProductColor");

                    b.HasOne("ToyCabin.Domain.Entities.InventoryDisposition", "ToDisposition")
                        .WithMany("ToInventoryTransactions")
                        .HasForeignKey("ToDispositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransaction_ToDisposition");

                    b.HasOne("ToyCabin.Domain.Entities.InventoryLocation", "ToLocation")
                        .WithMany("IncomingInventoryTransactions")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransaction_ToLocation");

                    b.Navigation("FromDisposition");

                    b.Navigation("FromLocation");

                    b.Navigation("ProductColor");

                    b.Navigation("ToDisposition");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Order", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.User", "Staff")
                        .WithMany("Orders")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Staff");

                    b.HasOne("ToyCabin.Domain.Entities.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Store");

                    b.Navigation("Staff");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("ToyCabin.Domain.Entities.ProductColor", "ProductColor")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_ProductColor");

                    b.Navigation("Order");

                    b.Navigation("ProductColor");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.PasswordResetOtp", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Account", "Account")
                        .WithMany("PasswordResetOtps")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetOtp_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Product", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.ProductCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ProductColor", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Product", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductColor_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Shelf", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Cabin", "Cabin")
                        .WithMany("Shelves")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Shelf_Cabin");

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ShelfSlot", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Shelf", "Shelf")
                        .WithMany("ShelfSlots")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShelfSlot_Shelf");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.User", "ApprovedByUser")
                        .WithMany("ApprovedShipments")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Shipment_ApprovedByUser");

                    b.HasOne("ToyCabin.Domain.Entities.InventoryLocation", "FromLocation")
                        .WithMany("FromShipments")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Shipment_FromLocation");

                    b.HasOne("ToyCabin.Domain.Entities.User", "RequestedByUser")
                        .WithMany("RequestedShipments")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Shipment_RequestedByUser");

                    b.HasOne("ToyCabin.Domain.Entities.InventoryLocation", "ToLocation")
                        .WithMany("ToShipments")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Shipment_ToLocation");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("FromLocation");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ShipmentItem", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.ProductColor", "ProductColor")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ShipmentItem_ProductColor");

                    b.HasOne("ToyCabin.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShipmentItem_Shipment");

                    b.Navigation("ProductColor");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ShipmentMedia", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Media")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShipmentMedia_Shipment");

                    b.HasOne("ToyCabin.Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedShipmentMedia")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ShipmentMedia_UploadedByUser");

                    b.Navigation("Shipment");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Store", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Partner", "Partner")
                        .WithMany("Stores")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Store_Partner");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.StoreInvitation", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Store", "Store")
                        .WithMany("StoreInvitations")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StoreInvitation_Store");

                    b.HasOne("ToyCabin.Domain.Entities.User", "User")
                        .WithMany("StoreInvitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StoreInvitation_User");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.User", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Partner", "Partner")
                        .WithMany("Users")
                        .HasForeignKey("PartnerId")
                        .HasConstraintName("FK_User_Partner");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.UserStore", b =>
                {
                    b.HasOne("ToyCabin.Domain.Entities.Store", "Store")
                        .WithMany("UserStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserStore_Store");

                    b.HasOne("ToyCabin.Domain.Entities.User", "User")
                        .WithMany("UserStores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserStore_User");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("PasswordResetOtps");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Cabin", b =>
                {
                    b.Navigation("CabinSnapshots");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.DamageReport", b =>
                {
                    b.Navigation("DamageMedia");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.InventoryDisposition", b =>
                {
                    b.Navigation("FromInventoryTransactions");

                    b.Navigation("Inventories");

                    b.Navigation("ToInventoryTransactions");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.InventoryLocation", b =>
                {
                    b.Navigation("DamageReports");

                    b.Navigation("FromShipments");

                    b.Navigation("IncomingInventoryTransactions");

                    b.Navigation("Inventories");

                    b.Navigation("OutgoingInventoryTransactions");

                    b.Navigation("ToShipments");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Partner", b =>
                {
                    b.Navigation("Stores");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductColors");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.ProductColor", b =>
                {
                    b.Navigation("DamageReports");

                    b.Navigation("Inventories");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("OrderItems");

                    b.Navigation("ShipmentItems");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Shelf", b =>
                {
                    b.Navigation("ShelfSlots");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Store", b =>
                {
                    b.Navigation("Cabins");

                    b.Navigation("InventoryLocations");

                    b.Navigation("Orders");

                    b.Navigation("StoreInvitations");

                    b.Navigation("UserStores");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ApprovedShipments");

                    b.Navigation("CabinSnapshots");

                    b.Navigation("Orders");

                    b.Navigation("ReportedDamageReports");

                    b.Navigation("RequestedShipments");

                    b.Navigation("ReviewedDamageReports");

                    b.Navigation("StoreInvitations");

                    b.Navigation("UploadedShipmentMedia");

                    b.Navigation("UserStores");
                });

            modelBuilder.Entity("ToyCabin.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("InventoryLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
